CREATE TABLE IF NOT EXISTS drivers (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  verified SMALLINT NOT NULL DEFAULT 0,
  is_available SMALLINT NOT NULL DEFAULT 0,
  lat FLOAT DEFAULT NULL,
  lng FLOAT DEFAULT NULL,
  password VARCHAR(255) NOT NULL
);