CREATE TABLE IF NOT EXISTS vendors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  owner_name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  phone VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL,
  service_available SMALLINT DEFAULT 0,
  food_type VARCHAR(50) DEFAULT NULL,
  cover_image VARCHAR(255) DEFAULT NULL,
  rating SMALLINT DEFAULT 0,
  lat FLOAT DEFAULT NULL,
  lng FLOAT DEFAULT NULL
);